dvc_config:
    DVC_REMOTE_URL: "https://dagshub.com/ravikirankiran097/GithubActionsMLOps.dvc"
    USERNAME: "ravikirankiran097"
    PASSWORD: "a6218961dad1404d4865c8400c5535c1a8cd103d"
  
model_data_config:
    MODEL_PATH: "./git_actions_models"
    METRICS_PATH: "./git_actions_data/metrics"

ec2_prepare:
    DAGSHUB_REMOTE_URL: "[MY REMOTE URL]"
    REQUIREMENTS: "requirements.txt"
    EC2_KEY_PAIR: "[PATH TO MY SECRET KEY]"

host_information:
    HOST: "github_actions_instance" # This is the name I gave my EC2 HOST in the ~/.ssh/config file
    EC2_USER:  "ec2-user"
    EC2_IP: "[MY IP ADDRESS]"
    EC2_REMOTE_DIRECTORY: "[MY REMOTE DIRECTORY]"

meta_data:
    DOCKERFILE: "./docker/Dockerfile"
    APP: "app.py"

mlflow_credentials: 
    MLFLOW_TRACKING_URI: "https://dagshub.com/ravikirankiran097/GithubActionsMLOps.mlflow"
    MLFLOW_TRACKING_USERNAME: "ravikirankiran097"
    MLFLOW_TRACKING_PASSWORD: "a6218961dad1404d4865c8400c5535c1a8cd103d"
